In [ ]:

import numpy as np
from src import eliminacion_gaussiana


def contar_operaciones(n):
    ops_sr = 0
    ops_md = 0

    # -----------------------
    # ELIMINACIÓN (estructura exacta)
    # -----------------------
    for i in range(0, n - 1):

        # búsqueda de pivote (no cuenta operaciones aritméticas)

        for j in range(i + 1, n):

            # m = A[j,i] / A[i,i]
            ops_md += 1

            # A[j, i:] = A[j, i:] - m * A[i, i:]
            columnas = (n + 1) - i
            ops_md += columnas
            ops_sr += columnas

    # -----------------------
    # SUSTITUCIÓN HACIA ATRÁS
    # -----------------------
    ops_md += 1

    for i in range(n - 2, -1, -1):

        terminos = n - 1 - i
        ops_md += terminos
        ops_sr += terminos

        ops_sr += 1
        ops_md += 1

    return ops_sr, ops_md


# -----------------------
# MATRICES REALES
# -----------------------

matrices = {
    2: np.array([[2, 1, -1],
                 [1, 0, 2]], dtype=float),

    3: np.array([[2, 1, -1, 0],
                 [1, 0, 2, 5],
                 [1, -2, 4, 5]], dtype=float),

    4: np.array([[1, 2, 3, 4, 1],
                 [2, 5, 6, 7, -2],
                 [3, 6, 8, 9, 3],
                 [4, 7, 9, 10, 4]], dtype=float),

    5: np.array([[2, 1, -1, 1, -3, 7],
                 [1, 0, 2, -1, 1, 2],
                 [0, -2, -1, 1, -1, -5],
                 [3, 1, -4, 0, 5, 7],
                 [1, -1, -1, -1, 1, 3]], dtype=float),

    6: np.array([[2, 1, -2, 1, -3, 7, 1],
                 [1, 0, -2, 2, -1, 1, 2],
                 [0, -2, -2, -1, 1, -1, -5],
                 [3, 1, -2, -4, 0, 5, 7],
                 [1, -1, -2, -1, -1, 1, 3],
                 [1, 2, -2, -1, 1, -3, 7]], dtype=float)
}

print(f"{'n':<5} | {'Ab_n':<6} | {'N sum./rest.':<15} | {'N mult./div.':<15}")
print("-" * 55)

for n, Ab in matrices.items():

    # ejecutar la función real
    eliminacion_gaussiana(Ab.copy())

    sr, md = contar_operaciones(n)

    print(f"{n:<5} | Ab{n:<4} | {sr:<15} | {md:<15}")


n     | Ab_n   | N sum./rest.    | N mult./div.   
-------------------------------------------------------
[02-18 15:57:13][INFO][Alex] 
[[ 1.  0.  2.]
 [ 0.  1. -5.]]
2     | Ab2    | 5               | 7              
[02-18 15:57:13][INFO][Alex] 
[[  1.   0.   2.   5.]
 [  0.   1.  -5. -10.]
 [  0.  -2.   2.   0.]]
[02-18 15:57:13][INFO][Alex] 
[[  1.   0.   2.   5.]
 [  0.   1.  -5. -10.]
 [  0.   0.  -8. -20.]]
3     | Ab3    | 16              | 20             
[02-18 15:57:13][INFO][Alex] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[02-18 15:57:13][INFO][Alex] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[02-18 15:57:13][INFO][Alex] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
4     | Ab4    | 35              | 42             
[02-18 15:57:13][INFO][Alex] 
[[  1.   0.   2.  -1.   1.   2.]
 [  0.   1.  -5.   3.  -5.   3.]
 [  0.  -2.  -